### ISSUE TITLE
rtc.sh: Unable to open file /etc/adjtime - read only

### ISSUE THREAD

**Issue by edru** [MiSTer-devel/Scripts_MiSTer#17]
When running rtc.sh I get the error during the process:

> hwclock: Could not open file with the clock adjustment parameters in it (/etc/adjtime) for writing:  Read-only file system.
hwclock: Drift adjustment parameters not updated.
RTC Set.

**Comment by Locutus73** [comment]
Fixed by https://github.com/MiSTer-devel/Scripts_MiSTer/commit/615d4c3eb3e2fa3eb3c0954995df991b3c8b4fc0
