### ISSUE TITLE
[Remove] Script build mame roms

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Scripts_MiSTer#23]
Hi,
Maybe we can removed this script because we used now MRA files
https://github.com/MiSTer-devel/Scripts_MiSTer/blob/master/other_authors/build_mame_roms.sh

What do you think ?
Thanks,

**Comment by selfslaughter** [comment]
Agreed. The scripts it calls are no longer on github anyway. It's no longer useful.

I sent loc a message a while back mentioning that. Just submitted a PR to remove it to make life easy for him.

**Comment by wwark** [comment]
Thank you I closed this ticket.
