### ISSUE TITLE
Cutting power at OSD corrupts exFAT fs

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Scripts_MiSTer#36]
It appears that if a `chkdsk`-validated microSD exFAT partition is used in MiSTer, and then MiSTer is simply powered off from the OSD, it somehow corrupts the "volume bitmap" of that partition.  At least, that's what `chkdsk` again reports if I remove the microSD from MiSTer and check it again on my Windows 10 PC.  I repeated this cycle a couple times to confirm the issue.

So then I wrote a quick `/media/fat/Scripts/shutdown.sh` that I can easily run from the OSD:

```bash
#!/bin/bash
echo Wait 5 seconds and then power off.
halt -f
```

As long as I use that shutdown script before powering down each time, then the exFAT partition still reads as good when I check the microSD again on my Windows PC.

So it seems the standard guidance about "just go to the OSD and power off" is still not great. It would be better to add a proper shutdown command to the main screen of the OSD (for convenience), so the user doesn't have to go hunting through the Scripts folder just to shut down.  
 For now, I created a symlink named `/media/fat/Scripts/_shutdown.sh` to force it to appear first in the sort order, but that's still a bit of a kludge.

FYI, I'm working on a better version of this shutdown script that uses `halt` rather than `halt -f`.  It requires making a couple small changes to `/etc/inittab` so that the "safe to shut down now" message doesn't get printed until after the shutdown sequence has actually completed.  I'll post a PR and a copy of `/etc/inittab` here when I have it "ship ready".  Also note that you won't be able to take this fix without also changing the "RememberPowered=true" in `/etc/bluetooth/main.conf` to `false` as described in https://github.com/MiSTer-devel/Main_MiSTer/issues/215, otherwise doing a proper shutdown with this script will permanently shutdown the Bluetooth adapter (and the user won't be able to get it to come back no matter how many times they reboot).

**Comment by sorgelig** [comment]
There WON'T be any shutdown procedure for MiSTer.
Probably there is a dummy flag in FAT volume set if any file is opened for write but didn't closed before unmounting. This is not indicator of corruption.

MiSTer is tuned for instant power off and will remain this way.

**Comment by c0d3h4x0r** [comment]
Is there any way the OSD could remount the exFAT as readonly while nothing else is running, but temporarily remount it as readwrite just before changing any settings or while running any core?  That way, the guidance to "reset to the OSD and kill the power" couldn't possibly corrupt the filesystem.

**Comment by sorgelig** [comment]
MiSTer has FTP/SSH/Samba access, so mounting in read-only mode is not correct. I almost never remove my SD card from MiSTer. And when i remove it, windows tells about possible corruption but never finds any real corruption.
But of course cutting the power while writing will make a damage. 
At the same time, even when it writes, in 99.9% cases it writes to existing file without changing the size. So even cutting the power while writing (which i of course don't recommend) will damage only this file. 
SD card is mounting in non-update time for file records, so simple write/read should not touch the catalog nor fat.

**Comment by sorgelig** [comment]
Btw, MiSTer is not a Windows and even not a normal Linux. It doesn't write itself to files if you don't ask to. So if you want a safe place to shutdown is to warm-reboot Menu core (short press of shift-ctrl-alt-alt or use reboot option on OSD). 
So warm-reboot Menu core, wait 5 seconds (in case if there was write in previous core, so it will be force flushed withing 5 secs max) and it's safe to shutdown.

**Comment by c0d3h4x0r** [comment]
> MiSTer has FTP/SSH/Samba access, so mounting in read-only mode is not correct.

Yeah, I realized that after I'd posted my suggestion.

>I almost never remove my SD card from MiSTer.

Me neither.

>And when i remove it, windows tells about possible corruption but never finds any real corruption.

I'm not talking about the Windows pop-up dialog complaining about possible corruption that sometimes appears on microSD insertion, though.  I see that whenever I insert any microSD containing an ext* partition on it, so I've learned to just ignore it.   I'm talking about the output of manually running **chkdsk /f** against the drive letter corresponding to the exFAT partition itself, which had me more concerned.

> But of course cutting the power while writing will make a damage.

Yep.  That's why I'm concerned.

>Btw, MiSTer is not a Windows and even not a normal Linux. It doesn't write itself to files if you don't ask to.

Are you sure about that?  While I was looking at **/etc/inittab* recently during my investigation of the Bluetooth stuff, I ssh'ed into MiSTer and ran `htop` while it was just sitting at the main OSD menu, and I noticed multiple background processes (such as `sync`, `bluetoothd`, and others) were active.  I don't know what they all do, but isn't it possible some of them could be writing to the exFAT even then?  Is there a way to monitor in real time which processes are writing to disk, to confirm none of them are writing while just sitting at the main menu?

**Comment by sorgelig** [comment]
sync is called from startup script every 5 seconds to force flush any possible pending writes. It doesn't write if no pending writes available. Actually MiSTer tries to mount all volumes in sync mode which means write asap without caching. Periodic sync call just enforces it in case if still something opened without sync mode. This is why i often say "wait for 5 seconds after you write something before shutting down." Also hard reboot called from keyboard (long press shift+ctrl+alt+alt) first calls sync. So it's also should be safe to do.

bluetoothd is eventually for BT dongles. It uses sandboxed mounted volume where it writes when you pair a new device. Otherwise it shouldn't write. Sync is also applied to this volume. 
I don't know what kind of activity you talking about. Of course there are some services requiring for MiSTer to work, but they aren't about writes.

>  BusyBox and other minimalist stuff. It's an extremely lean GNU/Linux :-)

It's just part of tweaks. There are many other tweaks like disabling access time update in catalogs, system volume is mounted in read-only (unless you log in to it), and many other things which you don't notice.

On I/O board the DISK led shows disk activity. So if it's not blinking, then there is no disk access at all.

**Comment by sorgelig** [comment]
As i've told earlier, in almost all cases even file is opened for writes, it doesn't change the file size. It means FAT and catalog is not affected. In worst case if some one is careless enough cut the power while some core does writes, then only content of this file will be damaged without affecting neither FAT nor catalog. So basically only some block in particular file will be damaged. 

Special case is when you use FTP or similar access and upload the files which heavily updates the FAT and catalog. In this case you should realize what are you doing and don't turn off the MiSTer.. This is obvious requirement and not covered by warranty :) 
Just after finish uploading wait for 5 seconds (ok, 6 seconds) and you are safe to shut it down.
So just watch and realize what are you doing. System basically is fool-proof but don't be a fool :)

**Comment by c0d3h4x0r** [comment]
Makes sense.  Thanks for all of the information!
