### ISSUE TITLE
error message from wifi.sh about printMsgs function not being defined

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Scripts_MiSTer#37]
When `wifi.sh` was copied over from the RetroPie project, the `printMsgs` function that it depends upon for displaying errors did not come along for the ride.  So when an error happens, all the user sees is the error about the missing `printMsgs` function, instead of the actual error they are supposed to see.

I'm preparing a fix to add it back.

**Comment by c0d3h4x0r** [comment]
PR published: https://github.com/MiSTer-devel/Scripts_MiSTer/pull/38

**Comment by kaloun34** [comment]
The missing function:

function printMsgs() {
    local type="$1"
    shift
    if [[ "$__nodialog" == "1" && "$type" == "dialog" ]]; then
        type="console"
    fi
    for msg in "$@"; do
        [[ "$type" == "dialog" ]] && dialog --backtitle "$__backtitle" --cr-wrap --no-collapse --msgbox "$msg" 20 60 >/dev/tty
        [[ "$type" == "console" ]] && echo -e "$msg"
        [[ "$type" == "heading" ]] && echo -e "\n= = = = = = = = = = = = = = = = = = = = =\n$msg\n= = = = = = = = = = = = = = = = = = = = =\n"
    done
    return 0
}

**Comment by wwark** [comment]
for wifi.sh, maybe we can replace printMsgs by an echo (shorter script better script).
We need also put clear in comment to print the message.

[wifi.zip](https://github.com/MiSTer-devel/Scripts_MiSTer/files/5684965/wifi.zip)

**Comment by Locutus73** [comment]
Fixed with https://github.com/MiSTer-devel/Scripts_MiSTer/pull/38
