### ISSUE TITLE
bluetooth_pair.sh does not find BT LE devices

### ISSUE THREAD

**Issue by jdeberhart** [MiSTer-devel/Scripts_MiSTer#39]
bluetooth_pair.sh does not find bluetooth LE devices.
While `hcitool lescan` finds bluetooth LE devices, the bluetooth pairing script does not.

This prevents many bluetooth keyboards and mice from being able to pair.

**Comment by sorgelig** [comment]
LE is not supported, sorry. 
Only classic BT. LE is completely different protocol although they still call it BT.

**Comment by c0d3h4x0r** [comment]
Is this issue still relevant?  I have a BTLE keyboard that pairs just fine with MiSTer ever since the Linux kernel was updated several months ago.

**Comment by sorgelig** [comment]
LE supported already
