### ISSUE TITLE
ini_settings.sh: save file in UNIX format

### ISSUE THREAD

**Issue by tjanas** [MiSTer-devel/Scripts_MiSTer#59]
This script calls unix2dos, which leaves trailing ^M (carriage return) characters at the end of each line. For consistency, it should keep this ini file in UNIX format.

**Comment by Locutus73** [comment]
Original MiSTer.ini uses CrLf line endings, so @sorgelig prefers it this way, probably for not confusing Windows users or for other reasons. So, for consistency reasons, ini_settings.sh complies to that.
